# Generated by Django 5.1.6 on 2025-03-13 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userquestionresult_result_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pud_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
