# Generated by Django 5.1.6 on 2025-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='theme_is_light',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(default='latte', max_length=16),
            preserve_default=False,
        ),
    ]
