# Generated by Django 5.1.6 on 2025-04-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userpreference_theme_is_light_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
