# Generated by Django 5.1.6 on 2025-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_pud_date_exam_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(default='latte', max_length=16),
        ),
    ]
