# Generated by Django 5.1.5 on 2025-02-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exum',
            new_name='Exam',
        ),
    ]
