# Generated by Django 5.1.6 on 2025-02-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_exum_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionresult',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exum',
        ),
        migrations.RemoveField(
            model_name='userquestionresult',
            name='exum',
        ),
        migrations.RemoveField(
            model_name='userquestionresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserQuestionResult',
        ),
    ]
